<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\apicampeonatosfifa.core\apicampeonatosfifa.core.csproj" />
    <ProjectReference Include="..\apicampeonatosfifa.dominio\apicampeonatosfifa.dominio.csproj" />
    <ProjectReference Include="..\apicampeonatosfifa.infreaestructura\apicampeonatosfifa.infraestructura.csproj" />
  </ItemGroup>

</Project>
